name: Bug Report
description: Something isn't working
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's broken?
      description: What happened and what did you expect?
      placeholder: "When I try to... it does... instead of..."
    validations:
      required: true
