name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: request
    attributes:
      label: What do you need?
      description: Describe what you want the app to do
      placeholder: "I want to be able to..."
    validations:
      required: true
