name: Feature Request
description: Suggest a new feature for FureverCare
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the use case?
      placeholder: "As a pet owner, I want to... so that..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the app does this affect?
      options:
        - Pet Profile
        - Health Records
        - Emergency Card
        - Sharing
        - Authentication
        - Dashboard
        - Documents/Uploads
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
      placeholder: Optional

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, links, or other helpful info
      placeholder: Optional
